### ISSUE TITLE
First steps at organizing the site

### ISSUE THREAD

**Issue by wbamberg** [openwebdocs/website#10]
Given some of the issues raised I thought it would be good to think a bit about how to organize things, even in our initial "just good enough" version of the website.

At the moment we have a site with:

- a list of links along the top (currently only "About us"). The theme calls this the "menu" so I will do the same here
- a list of links to blog posts down the main page (currently only the MD post)

<img width="1112" alt="Screen Shot 2022-03-17 at 12 35 00 PM" src="https://user-images.githubusercontent.com/432915/158881732-2e67fde6-66b8-43f9-bfb4-c87eaa24afba.png">

So we can have a few more things in the menu, and will of course expect to get more blog posts listed in the main page. We can also pin blog posts, which I think might turn out to be handy.

The additional (non-blog) pages that people have asked for so far are:
- Get involved
- Link to Open Collective (labelled "Donate")
- Membership levels (not ready yet)
- Current OWD impact report

I'm guessing meeting notes should be considered blog posts, and I don't think they merit inclusion in the menu. But I think we should limit the number of menu items to 4 or 5. It might also be nice to have a link to the blog archive in the menu.

So a couple of choices:

In the menu:
- Blog
- About us
- Get involved
- Donate

Pinned as a blog post:
2021 Impact report

<img width="1118" alt="Screen Shot 2022-03-17 at 12 54 14 PM" src="https://user-images.githubusercontent.com/432915/158884725-6484da1d-ca17-4dce-b495-8eac94316808.png">

**or** have the impact report as a separate item in the menu:

<img width="1100" alt="Screen Shot 2022-03-17 at 12 53 02 PM" src="https://user-images.githubusercontent.com/432915/158884498-5aca3a7a-8d84-4bb4-9c3a-23dbc01bf265.png">

Having tried these both out, I like the second one better, with the IR as a dedicated menu item.

A couple of other notes:
- not sure what's a good order for menu items
- I have used title case for menu items ("About **U**s") because it looks better for the IR, and it looks weird not being consistent.

**Comment by wbamberg** [comment]
Oh, also. For blog posts I think we could have at least the following categories:
- projects
- steering committee meeting notes (a bit long this)
- reports (for quarterly IA reports)
- planning, maybe, for posts about, well, planning work in the next Quarter?

(or something like that)

These become tags, and you can then see tagged posts with a link like https://inspiring-snyder-9401af.netlify.app/tags/projects/

**Comment by Elchi3** [comment]
> Having tried these both out, I like the second one better, with the IR as a dedicated menu item.

Yes, I think I like it more, too.

> Oh, also. For blog posts I think we could have at least the following categories:
> 
> * projects
> * steering committee meeting notes (a bit long this)
> * reports (for quarterly IA reports)
> * planning, maybe, for posts about, well, planning work in the next Quarter?

Ah yes, this is fantastic! It solves my question in https://github.com/openwebdocs/website/issues/7

**Comment by Elchi3** [comment]
I believe we got this done in #11.
