### ISSUE TITLE
Confusing placement for dark/light theme switch 

### ISSUE THREAD

**Issue by dontcallmedom** [openwebdocs/website#19]
Next to the title, it looks like the moon icon is OWD's logo

**Comment by wbamberg** [comment]
Do you think over by the Impact Report link would work?

**Comment by dontcallmedom** [comment]
possibly - although given that this is rather accessory (and ideally, something that gets picked automatically via browser setting), maybe it can be hidden further down (e.g. in the footer); but then again, I'm not much of a designer :)

**Comment by Elchi3** [comment]
I merged https://github.com/openwebdocs/website/pull/20 which removes it and just relies on user settings.
