### ISSUE TITLE
Add posts from Open Collect page

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/website#21]
Open Web Docs was launched in January 2021 and there are quite a few interesting posts that we published on our Open Collect page since then. It would be good to have them on our website so that the website has the full context of OWD. When importing these posts, we probably want to think about when a post is in some sort of archive so that e.g. the homepage only shows the current, most interesting content.

**Comment by wbamberg** [comment]
> Open Web Docs was launched in January 2021 and there are quite a few interesting posts that we published on our Open Collect page since then. It would be good to have them on our website so that the website has the full context of OWD. When importing these posts, we probably want to think about when a post is in some sort of archive so that e.g. the homepage only shows the current, most interesting content.

It looks like the theme has pagination, so it will only show you the most recent 5 posts (https://adityatelange.github.io/hugo-PaperMod/) - I don't know if that number is configurable. But that might help with this?

**Comment by Elchi3** [comment]
Yes, that's probably good enough.

Should we just open a PR that adds all the content and then see if we need to optimize anything?
