### ISSUE TITLE
Create a page for sponsors

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/website#5]
(updated)

We should have a page that talks about the companies and people that sponsor us.

For later: The OWD Governing Committee is currently working on membership levels. Once/If we agreed on them, we can mention our sponsoring levels on this page, too.

**Comment by Elchi3** [comment]
Prior art:

- https://obsproject.com/contribute 
- https://babeljs.io
- https://foundation.rust-lang.org/members/
- https://webpack.js.org

**Comment by lolaodelola** [comment]
Will this need to use the Open Collective API so that folks can donate directly from the site?

**Comment by wbamberg** [comment]
I think it would be enough to link to Open Collective, wouldn't it? That looks like the approach those other pages are taking.

**Comment by Elchi3** [comment]
Yeah, I think it can be manual. We only have a handful of sponsors that we want to categorize using our membership levels for the moment.

**Comment by Elchi3** [comment]
I updated this issue to unblock us. For now we want a page that presents our main sponsors.

**Comment by wbamberg** [comment]
As we discussed, it would be good then to reconsider which pages we want in the menu and how they interrelate. We are looking at:

- Impact Report
- Blog
- About Us
- Get Involved
- Sponsors
- Donate (link to Open Collective)=

That's 6, which is a bit more than we might like, and at least the last 4 are quite closely related. We could have separate pages but we might consider merging some of them. I think we should have separate pages for Donate and Sponsors, but perhaps we could include "Get Involved" under "About Us"?

Or perhaps it's OK having 6 pages here and I am worrying needlessly :).

**Comment by wbamberg** [comment]
https://github.com/openwebdocs/website/pull/18 adds a page listing main sponsors.

**Comment by Elchi3** [comment]
Closing, given we have that page now.
