### ISSUE TITLE
Create a page for the current OWD impact & transparency report

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/website#6]
Currently, the impact report lives here: https://github.com/openwebdocs/project/tree/main/impact-report-2021
It would be good to give it a proper page on our website where we control a good rendering of it. 

However, I'm unsure how we want to version it. Ideally, openwebdocs.org/impact-report is always the latest quarter. 
Maybe the 2021 (and other dated reports) live on GitHub?

**Comment by wbamberg** [comment]
I had thought we could have a dedicated link to "Impact Report 2021" in the menu, update that every year, and publish the quarterly ones in the blog with a "impact report" tag.

**Comment by Elchi3** [comment]
Will got this done :)
